# https://blog.ekbana.com/fine-tuning-bert-for-text-classification-20news-group-classification-53a55dc09738
* SEQ_LEN is a number of lengths of the sequence after tokenizing. It is set to 128. BERT has worked on at max 512 sequence length.
* LR is the learning rate.
* 

In [2]:
import codecs
import tensorflow as tf
from tqdm import tqdm
from chardet import detect

In [20]:
from tensorflow import keras
#from keras_radam import RAdam
#from keras import backend as K

In [23]:
#from keras_bert import load_trained_model_from_checkpoint
from keras_bert.keras_bert.bert import get_model

ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

In [22]:
pretrained_path='C:\Xiaoyu\jupyter_notebooks\data\Bert\cased_L-12_H-768_A-12'
config_path=os.path.join(pretrained_path,'bert_config.json')
checkpoint_path=os.path.join(pretrained_path, 'bert_model.ckpt.data-00000-of-00001')
vocab_path=os.path.join(pretrained_path, 'vocab.txt')

In [15]:
model=loan_trained_model_from_checkpoint(
    config_path,
    checkpoint_path,
    training=True,
    trainable=True,
    seq_len=SEQ_LEN
)

NameError: name 'loan_trained_model_from_checkpoint' is not defined

#2 https://www.kaggle.com/sergeykalutsky/introducing-bert-with-tensorflow

In [4]:
import pandas as pd
import os
import numpy as np
import pandas as pd
import zipfile
from matplotlib import pyplot as plt
%matplotlib inline
import sys
import datetime

#downloading weights and cofiguration file for the model
#!wget https://storage.googleapis.com/bert_models/2018_10_18/uncased_L-12_H-768_A-12.zip

* This is one of the smaller BERT models (English only, uncased, trained with WordPiece masking). beyond BERT-Base and BERT-Large. The smaller BERT models are intended for environments with restricted computational resources. They can be fine-tuned in the same manner as the original BERT models. However, they are most effective in the context of knowledge distillation, where the fine-tuning labels are produced by a larger and more accurate teacher.
* 





In [10]:
path='C:\Xiaoyu\jupyter_notebooks\data\Bert\small_bert_bert_uncased_L-12_H-768_A-12_1.zip'

In [11]:
repo = 'model_repo'
with zipfile.ZipFile(path,"r") as zip_ref:
    zip_ref.extractall(repo)

BadZipFile: File is not a zip file

#3 https://analyticsindiamag.com/bert-classifier-with-tensorflow-2-0/

In [24]:
import tensorflow_hub as hub
from tensorflow.keras.models import Model
from bert.tokenization.bert_tokenization import FullTokenizer

In [25]:
bert_layer = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/1",trainable=True)

#4 https://androidkt.com/simple-text-classification-using-bert-in-tensorflow-keras-2-0/

In [28]:
# %tensorflow_version 2.x
 
import tensorflow as tf
import tensorflow_hub as hub
import bert
from tensorflow.keras.models import  Model
from tqdm import tqdm
import numpy as np
from collections import namedtuple
print("TensorFlow Version:",tf.__version__)
print("Hub version: ",hub.__version__)

TensorFlow Version: 2.1.0
Hub version:  0.8.0


# Bert Embedding Layer
* For finetuning, the BERT model is first initialized with the pre-trained parameters, and all of the parameters are fine-tuned using labeled data from the downstream tasks.

In [29]:
bert_layer=hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/1",trainable=True)

In [30]:
MAX_SEQ_LEN=128
input_word_ids = tf.keras.layers.Input(shape=(MAX_SEQ_LEN,), dtype=tf.int32,
                                       name="input_word_ids")
input_mask = tf.keras.layers.Input(shape=(MAX_SEQ_LEN,), dtype=tf.int32,
                                   name="input_mask")
segment_ids = tf.keras.layers.Input(shape=(MAX_SEQ_LEN,), dtype=tf.int32,
                                    name="segment_ids")

In [31]:
def get_masks(tokens, max_seq_length):
    return [1]*len(tokens) + [0] * (max_seq_length - len(tokens))
 
def get_segments(tokens, max_seq_length):
    """Segments: 0 for the first sequence, 1 for the second"""
    segments = []
    current_segment_id = 0
    for token in tokens:
        segments.append(current_segment_id)
        if token == "[SEP]":
            current_segment_id = 1
    return segments + [0] * (max_seq_length - len(tokens))

In [32]:
pooled_output, sequence_output = bert_layer([input_word_ids, input_mask, segment_ids])

# Tokenization
* During any text data preprocessing, there is a tokenization phase involved. The tokenizer available with the BERT package is very powerful. We use WordPiece embeddings (Wu et al., 2016) with a 30,000 token vocabulary.  Create the tokenizer with the BERT layer and import it tokenizer using the original vocab file.

In [33]:
FullTokenizer=bert.bert_tokenization.FullTokenizer
 
vocab_file=bert_layer.resolved_object.vocab_file.asset_path.numpy()
 
do_lower_case=bert_layer.resolved_object.do_lower_case.numpy()
 
tokenizer=FullTokenizer(vocab_file,do_lower_case)
 
def get_ids(tokens, tokenizer, max_seq_length):
    """Token ids from Tokenizer vocab"""
    token_ids = tokenizer.convert_tokens_to_ids(tokens,)
    input_ids = token_ids + [0] * (max_seq_length-len(token_ids))
    return input_ids

# Prepare training data
* Our BERT embedding layer will need three types of input tokens: word_ids, input_mask, segment_ids. Applying the tokenizer to converting into words into ids. These are some functions that will be used to preprocess the raw text data into useable Bert inputs.
* The first token of every sequence is always a special classification token ([CLS]). It is a special symbol added in front of every input example and [SEP] is a special separator token is added at the end of every input example.

In [35]:
import pandas as pd
 
df=pd.read_csv(r'C:\Xiaoyu\jupyter_notebooks\data\toxic-comments-classification\train.csv')
 


In [39]:
import numpy as np

In [36]:
print(df.info())
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159571 entries, 0 to 159570
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype 
---  ------         --------------   ----- 
 0   id             159571 non-null  object
 1   comment_text   159571 non-null  object
 2   toxic          159571 non-null  int64 
 3   severe_toxic   159571 non-null  int64 
 4   obscene        159571 non-null  int64 
 5   threat         159571 non-null  int64 
 6   insult         159571 non-null  int64 
 7   identity_hate  159571 non-null  int64 
dtypes: int64(6), object(2)
memory usage: 9.7+ MB
None


(159571, 8)

In [37]:
df = df.sample(frac=1)
train_sentences = df["comment_text"].fillna("CVxTz").values
list_classes = ["toxic", "severe_toxic", "obscene", "threat", "insult", "identity_hate"]
train_y = df[list_classes].values

In [43]:
train_y

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [44]:
def create_single_input(sentence,MAX_LEN):
  
  stokens = tokenizer.tokenize(sentence)
  
  stokens = stokens[:MAX_LEN]
  
  stokens = ["[CLS]"] + stokens + ["[SEP]"]
 
  ids = get_ids(stokens, tokenizer, MAX_SEQ_LEN)
  masks = get_masks(stokens, MAX_SEQ_LEN)
  segments = get_segments(stokens, MAX_SEQ_LEN)
 
  return ids,masks,segments
 
def create_input_array(sentences):
 
  input_ids, input_masks, input_segments = [], [], []
 
  for sentence in tqdm(sentences,position=0, leave=True):
  
    ids,masks,segments=create_single_input(sentence,MAX_SEQ_LEN-2)
 
    input_ids.append(ids)
    input_masks.append(masks)
    input_segments.append(segments)
 
  return [np.asarray(input_ids, dtype=np.int32), 
            np.asarray(input_masks, dtype=np.int32), 
            np.asarray(input_segments, dtype=np.int32)]

# create and train model
* Each downstream task has separate fine-tuned models, even though they are initialized with the same pre-trained parameters. A simple classification layer is added to the pre-trained model, and all parameters are jointly fine-tuned on a downstream task.
* It’s simple, just taking the sequence_output of the bert_layer and pass it to an AveragePooling layer and finally to an output layer of 6 units (6 classes that we have to predict.

In [45]:
x = tf.keras.layers.GlobalAveragePooling1D()(sequence_output)
x = tf.keras.layers.Dropout(0.2)(x)
out = tf.keras.layers.Dense(6, activation="sigmoid", name="dense_output")(x)
 
model = tf.keras.models.Model(
      inputs=[input_word_ids, input_mask, segment_ids], outputs=out)
 
model.compile(loss='binary_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy'])

# Predict
* To predict new text data, first, we need to convert into BERT input after that you can use predict() on the model.

In [46]:
test_df=pd.read_csv(r'C:\Xiaoyu\jupyter_notebooks\data\toxic-comments-classification\test.csv')
 
test_sentences = test_df["comment_text"].fillna("CVxTz").values
 
test_inputs=create_input_array(test_sentences[110:150])
 
print(model.predict(test_inputs))

100%|█████████████████████████████████████████████████████████████████████████████████| 40/40 [00:00<00:00, 240.16it/s]


[[0.37743795 0.5032524  0.36082888 0.4743061  0.4435608  0.44272467]
 [0.45251027 0.4479136  0.4268136  0.5452405  0.4135311  0.4892719 ]
 [0.43675077 0.43947324 0.39971295 0.49904227 0.44394007 0.45059916]
 [0.4541468  0.5320734  0.42568192 0.4314642  0.4312399  0.4241745 ]
 [0.34689012 0.4800002  0.16000083 0.19137582 0.47779992 0.2825382 ]
 [0.4497849  0.4733316  0.37166736 0.39916587 0.5139005  0.4769495 ]
 [0.32739604 0.51324224 0.22877367 0.3796395  0.45445153 0.49720812]
 [0.42880595 0.4402787  0.40043503 0.5115382  0.48152542 0.49200475]
 [0.39209962 0.5332365  0.36057574 0.5318412  0.514612   0.4538718 ]
 [0.33492756 0.49402437 0.27535978 0.286611   0.41664496 0.44309935]
 [0.3736783  0.46415707 0.3614941  0.39193165 0.4623029  0.40315616]
 [0.40875033 0.5123575  0.37445122 0.55883235 0.46571255 0.52478343]
 [0.42466074 0.5023575  0.3366328  0.5229919  0.4443684  0.41407758]
 [0.4218307  0.42763475 0.43652135 0.53824884 0.47313827 0.4627886 ]
 [0.46842942 0.47757012 0.3989345 